services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "$MONGO_URI"
      - key: JWT_SECRET
        value: "$JWT_SECRET"
      - key: PORT
        value: "5000"
